project:
  type: website
  pre-render: 
    - "rm -rf _site/*"
  post-render:
    - "python scripts/post-render.py"
  resources:
    - CNAME
  preview:
    port: 7777

website:
  title: "Random Realizations"
  site-url:  https://randomrealizations.com/
  description: "A blog about data science, statistics, machine learning, and the scientific method"
  favicon: "favicon.png"
  margin-header: includes/subscribe.html
  # comments:
  #   utterances:
  #     repo: mcb00/blog
  #     issue-term: title
  image: logo-enso-white-background.png
  image-alt: circle painted by hand in a single brush stroke
  navbar:
    background: dark
    logo: logo.png
    right:
      - text: About
        href: about.qmd
      - text: Archive
        href: archive.qmd
      - text: Series
        menu:
          - text: Gradient Boosting Series
            href: gradient-boosting-series.qmd
      - text: Resources
        menu:
          - text: Python-Bloggers
            href: https://python-bloggers.com/
          
    tools:
      - icon: github
        href: https://github.com/mcb00
        text: Matt on Github
      - icon: twitter
        href: https://twitter.com/mcbwrs
        text: Matt on Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/matt-bowers
        text: Matt on Linkedin
format:
  html:
    theme: yeti # zephyr
      # light: flatly
      # dark: darkly
    css: styles.css
    include-in-header:
      - includes/umami.html



