project:
  type: website
  pre-render: "rm -rf _site/*"

website:
  title: "Random Realizations"
  site-url:  https://mattbowers.dev/rr-blog
  description: "A blog about data science, statistics, machine learning, and the scientific method"
  margin-header: subscribe.html
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Gradient Boosting Series
        href: gradient-boosting-series.qmd
    tools:
      - icon: github
        href: https://github.com/mcb00
        text: Matt on Github
      - icon: twitter
        href: https://twitter.com/mcbwrs
        text: Matt on Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/matt-bowers
        text: Matt on Linkedin
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



