project:
  type: website
  pre-render: "rm -rf _site/*"

website:
  title: "Random Realizations"
  site-url: https://blog.mattbowers.dev
  description: "A blog about data science, statistics, machine learning, and the scientific method"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Gradient Boosting
        href: gradient-boosting-series.qmd
      - icon: github
        href: https://github.com/mcb00
      - icon: twitter
        href: https://twitter.com/mcbwrs
format:
  html:
    theme:
      light: flatly
      dark: darkly

    css: styles.css



