project:
  type: website

website:
  title: "Random Realizations"
  description: "A blog about data science, statistics, machine learning, and the scientific method"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mcb00
      - icon: twitter
        href: https://twitter.com/mcbwrs
format:
  html:
    theme:
      light: flatly
      dark: darkly

    css: styles.css



